### ISSUE TITLE
[Sprint] Add convert (TFLite int8) and benchmark for Alif Ensemble DevKit Gen2 and Renesas RA8D1

### ISSUE THREAD

**Issue by Only-bottle** [Nota-NetsPresso/netspresso-python#51]
## Description

- Add convert (TFLite int8) and benchmark for Alif Ensemble DevKit Gen2 and Renesas RA8D1

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `develop`) branch.
- [x] This issue only contains a preceding agreement between project owners.

## Todo
- [x] Add int8 data type for TFLite converting
- [x] Add Alif Ensemble DevKit Gen2 adn Renesas RA8D1 on target devices
